services:
  - type: web
    name: texas-real-estate
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
